### ISSUE TITLE
license?

### ISSUE THREAD

**Issue by slivingston** [shadow-robot/smart_grasping_sandbox#17]
Can you add a top-level statement of licenses under which the source code is released?

I am motivated to ask because I noticed that the `fh_desc` package has [package.xml that declares the license as "Private"](https://github.com/shadow-robot/smart_grasping_sandbox/blob/6db2168821365cc464bf75ac3ed065e62506619e/fh_desc/package.xml#L7), which is ambiguous.

For comparison, the other two packages, [smart_grasping_sandbox](https://github.com/shadow-robot/smart_grasping_sandbox/blob/6db2168821365cc464bf75ac3ed065e62506619e/smart_grasping_sandbox/package.xml#L9) and [smart_grasp_moveit_config](https://github.com/shadow-robot/smart_grasping_sandbox/blob/6db2168821365cc464bf75ac3ed065e62506619e/smart_grasp_moveit_config/package.xml#L11), have package.xml that declares GPLv3 and BSD, respectively.

**Comment by ugocupcic** [comment]
@slivingston Thanks for pointing it out. I need to clarify that indeed... I'll update as soon as possible.

**Comment by ugocupcic** [comment]
It'll be GPLv3
