### ISSUE TITLE
How to solve dial tcp i/o timeout?

### ISSUE THREAD

**Issue by b2220333** [shadow-robot/smart_grasping_sandbox#24]
I have tried many times to run but failed.

    sudo docker run -it --name sgs -p 8080:8080 -p 8888:8888 -p 8181:8181 -p 7681:7681 shadowrobot/smart_grasping_sandbox

log:

    sam@sam:~$ sudo docker run -it --name sgs -p 8080:8080 -p 8888:8888 -p 8181:8181 -p 7681:7681 shadowrobot/smart_grasping_sandbox
    Unable to find image 'shadowrobot/smart_grasping_sandbox:latest' locally
    latest: Pulling from shadowrobot/smart_grasping_sandbox
    1d8592394ba1: Downloading [=====================================>             ]  50.27MB/67.11MB
    01aa7f61ccd1: Download complete 
    5dd2552a960e: Download complete 
    7cbe941c5e3e: Download complete 
    2549ecfb14c6: Downloading 
    9b8709a7a04d: Downloading 
    8db5e465681f: Waiting 
    181db3f32385: Waiting 
    18c4e5e428f4: Waiting 
    2e8934e82868: Waiting 
    864452181e1c: Waiting 
    60f2c78cb484: Waiting 
    e47593aa1eca: Waiting 
    923d9100556d: Waiting 
    9b19479c67ec: Waiting 
    ffe8a2851650: Waiting 
    ce7214044c33: Waiting 
    d064dae391d4: Waiting 
    e15008df3e2c: Waiting 
    39b52286e153: Downloading 
    316389c2f5e9: Downloading 
    95c21321a616: Downloading 
    55e6b1afa70a: Downloading 
    a1824faed13a: Downloading [==>                                                ]  4.859MB/88.59MB
    25b81594f6d0: Download complete 
    e848435af322: Download complete 
    7ea8900e92a3: Downloading 
    028a29b99d08: Waiting 
    docker: dial tcp: lookup registry-1.docker.io on 127.0.1.1:53: read udp 127.0.0.1:35213->127.0.1.1:53: i/o timeout.
    See 'docker run --help'.
    sam@sam:~$ sudo docker run -it --name sgs -p 8080:8080 -p 8888:8888 -p 8181:8181 -p 7681:7681 shadowrobot/smart_grasping_sandbox
    [sudo] password for sam: 
    Unable to find image 'shadowrobot/smart_grasping_sandbox:latest' locally
    latest: Pulling from shadowrobot/smart_grasping_sandbox
    1d8592394ba1: Downloading [=================================================> ]  65.83MB/67.11MB
    01aa7f61ccd1: Download complete 
    5dd2552a960e: Download complete 
    7cbe941c5e3e: Download complete 
    2549ecfb14c6: Download complete 
    9b8709a7a04d: Downloading 
    8db5e465681f: Downloading 
    181db3f32385: Downloading 
    18c4e5e428f4: Downloading 
    2e8934e82868: Downloading 
    864452181e1c: Downloading 
    60f2c78cb484: Download complete 
    e47593aa1eca: Downloading [========>                                          ]  12.43MB/69.87MB
    923d9100556d: Downloading 
    9b19479c67ec: Waiting 
    ffe8a2851650: Waiting 
    ce7214044c33: Waiting 
    d064dae391d4: Waiting 
    e15008df3e2c: Waiting 
    39b52286e153: Waiting 
    316389c2f5e9: Waiting 
    95c21321a616: Waiting 
    55e6b1afa70a: Waiting 
    a1824faed13a: Waiting 
    25b81594f6d0: Waiting 
    e848435af322: Waiting 
    7ea8900e92a3: Waiting 
    028a29b99d08: Waiting 
    docker: dial tcp: lookup auth.docker.io on 127.0.1.1:53: read udp 127.0.0.1:54704->127.0.1.1:53: i/o timeout.
    See 'docker run --help'.
    sam@sam:~$ 

My docker installation seems success:

    sam@sam:~$ sudo docker run hello-world
    Unable to find image 'hello-world:latest' locally
    latest: Pulling from library/hello-world
    b04784fba78d: Pull complete 
    Digest: sha256:f3b3b28a45160805bb16542c9531888519430e9e6d6ffc09d72261b0d26ff74f
    Status: Downloaded newer image for hello-world:latest
    
    Hello from Docker!
    This message shows that your installation appears to be working correctly.
    
    To generate this message, Docker took the following steps:
     1. The Docker client contacted the Docker daemon.
     2. The Docker daemon pulled the "hello-world" image from the Docker Hub.
     3. The Docker daemon created a new container from that image which runs the
        executable that produces the output you are currently reading.
     4. The Docker daemon streamed that output to the Docker client, which sent it
        to your terminal.
    
    To try something more ambitious, you can run an Ubuntu container with:
     $ docker run -it ubuntu bash
    
    Share images, automate workflows, and more with a free Docker ID:
     https://cloud.docker.com/
    
    For more examples and ideas, visit:
     https://docs.docker.com/engine/userguide/
    
    sam@sam:~$ 

What can I do next?

Thank you~

**Comment by ugocupcic** [comment]
Hi,

Sorry this looks like a Docker issue... :(  Do you have an up to date docker?

Can you try running: 

```
docker pull shadowrobot/smart_grasping_sandbox
```

This is working here (not very helpful for you I know :S )

Cheers,

Ugo
