### ISSUE TITLE
ignore collision between the table and the fingertips / the ball and the fingers

### ISSUE THREAD

**Issue by ugocupcic** [shadow-robot/smart_grasping_sandbox#4]

**Comment by ugocupcic** [comment]
@beatrizleon you did something like that at some point I believe?

**Comment by beatrizleon** [comment]
yes, here:
https://github.com/shadow-robot/sr_manipulation/blob/indigo-devel/sr_manipulation_simulation/src/sr_manipulation_simulation/pick_place.py#L25
